version: '3.8'

services:

  db:
    container_name: postgres
    image: postgres:alpine
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
      POSTGRES_DB: service_login
    ports:
      - "5432:5432"
    networks:
      - postgres-compose-network

  pgadmin:
    container_name: pgadin4
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "1542:80"
    networks:
      - postgres-compose-network

networks:
  postgres-compose-network:
    driver: bridge